apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecreamorder
  labels:
    app: icecreamorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecreamorder
  template:
    metadata:
      labels:
        app: icecreamorder
    spec:
      containers:
        - name: icecreamorder
          image: username/icecreamorder:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5